name: cga
description: A new Flutter project.

dependencies:
  http: "^0.11.3+16"
  flutter:
    sdk: flutter
  chewie: "^0.6.1"
  url_launcher: "^3.0.3"

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

